### ISSUE TITLE
Anesthetic hediff causes pawns to remain stuck inside MedPods

### ISSUE THREAD

**Issue by FGRemastered** [sumghai/MedPod#29]
Title says it all.

**Comment by sumghai** [comment]
> Title says it all.

While this particular bug was easy to reproduce with just Core and MedPod, please don't make a habit of "title says it all" in your future issue reports - instead, well-documented, non-sarcastic reports describing your game/mod version(s), how you reproduced the bug and what the expected behaviour should be would be much more appreciated.

Also, please don't tag "Bug", "Feature", "Idea", "Discussion", "Rant", "Complaint" etc. in your issue title. I will do that using GitHub's own label system once I myself have determined which category the issue best belongs to.

**Comment by sumghai** [comment]
Fixed in ce42a67

**Comment by FGRemastered** [comment]
I know how to make a proper bug report, but I deemed it unnecessary in this special case.
