### ISSUE TITLE
Support for the Lush and Stoner traits from Vanilla Traits Expanded

### ISSUE THREAD

**Issue by UntouchedWagons** [sumghai/MedPod#59]
**Describe your idea:**

VTE adds two traits that mess with the MedPod: Lush and Stoner. The former makes it impossible for a pawn to get over an alcohol addiction and the later is the same but for smokeleaf. If a pawn has either of these traits and enters the medpod, they'll never leave because the medpod can't remove the addiction hediffs.

**Why do you think your idea would be a good fit for MedPod?:**

It would improve compatibility with other trait mods not yet supported.

**What alternatives/workarounds have you tried?**

Stopping the medpod treatment process which doesn't really solve the issue.

## Declaration
I hereby verify that:
- [X] I have searched the issue tracker and confirmed no-one else has already suggested my idea before
- [X] I understand that my idea will be closed and ignored if I do not fill this form properly, or if the mod author decides that my idea doesn't fit the scope of the mod

**Comment by sumghai** [comment]
Lore-wise, the MedPod was developed by a culture that disapproves of chemical addictions, and MedPods in-universe aren't intended to be programmed/configured by patients to only selectively treat ailments - ignoring bionics and prosthetics, every hediff considered "bad" by the game gets removed.

Having the MedPod respect patient ideology and ignore addictions not only goes against my mod's design lore, but it also opens up a whole new set of complications if people request the ignoring of other precept-related hediffs like scarification, or even a pick-and-choose list of hediffs in general to ignore. This is meant to be a simple to use mod, not a fiddly one.

One possibility, however, would be that cultures with these ideos could need to modify or "hack" a MedPod with a special craftable "ethical override" component, which would then allow some precepts/memes/traits to be honored.

Thoughts?

**Comment by UntouchedWagons** [comment]
From the steam page for the mod:

    Rabbie The Moonrabbit - MedPods will ignore the rabbit lolis' Planetarium addictions

The medpod designers seemed okay with designing their medpod to ignore that.

**Comment by sumghai** [comment]
> From the steam page for the mod:
> 
> ```
> Rabbie The Moonrabbit - MedPods will ignore the rabbit lolis' Planetarium addictions
> ```
> 
> The medpod designers seemed okay with designing their medpod to ignore that addiction.

According to the Rabbie race mod lore, the Rabbie's dependence on Planetarium operates at a *racial* or *genetic* level, and they would actually die without Planetarium. The implication is that MedPods aren't so much deliberately programmed to actively ignore Planetarium addiction, but rather, they simply don't recognize it as a treatable condition for Rabbies in the first place.

VTE's Lush and Stoner traits are, despite their description text, tied to a pawn's culture or personal choice. The MedPod doesn't *ask* a (usually unconscious) patient what its beliefs/preferences are, but simply treats the patient according to what their "baseline state" should be.

In the event I do decide to support the VTE Lush and Stone traits, I'll have to implement a Rimatomics-like "upgrade" module system that would require players like you to explicitly install a craftable Ethics Override circuit to tell the corresponding MedPod to ignore addictions in pawns with those traits.

> But seriously, I would like to see some toggles on the medpod for what it can and can't treat. For example being able to treat addictions turns drugs from a "Is it worth the risk?" to "Yeah give 'em all Go-Juice, the medpod will clean them all up"; 

While this is a common request, I have no plans to implement a toggleable list hediffs to treat or ignore.

- There are many, many hediffs in the base game and third party mods, which would result in a very large switchboard-style dialog window.

- Uninstalling third-party mods that adds new hediffs will break the configuration file storing the hediff list due to NullRefExceptions.

- Some hediffs are interrelated to each other, and a user could easily and unknowingly break their game by toggling one hediff to be always treatable while making a related hediff to be non-treatable.

- Adding mod options exponentially increases my mod development, maintenance and bug support workload, and in this case the costs greatly outweigh the benefits.

- The source material (Neil Blompkamp's *Elysium*) does not depict MedPods as having customizable options. Patients are loaded onto the beds, treated, and discharged with minimal setup.

> or being able to regenerate missing limbs using only electricity significantly reduces the importance of prosthetics and bionics. It makes body purists' losing limbs a total non-issue.

The intention was to lock MedPod behind very high research and/or crafting requirements, so that it is harder for colonies to replace lost body parts in pawns. However, many users have previously complained about MedPod and Replimat being almost impossible to build, so I've rebalanced the difficulty/availability of acquiring the technology/components.

In the long term, I plan to tie MedPod and Replimat into my upcoming Lethe spacer mod, with a dedicated research tree and crafting chain for the various Isolinear components, which should strike a better balance in game/mod/tech challenge. But I digress.

**Comment by sumghai** [comment]
Come to think of it, maybe the MedPod should remove those traits altogether during treatment?

**Comment by sumghai** [comment]
@UntouchedWagons

I consulted with Oskar, Chowder and the other Vanilla Expanded team members who authored VTE, and they agreed that the MedPod should simply remove both traits, and notify the player with a letter:

*[PAWN_name] has had their underlying addiction removed, and now no longer has the [Trait_name] trait.*

**Comment by UntouchedWagons** [comment]
That'll do.

**Comment by sumghai** [comment]
@UntouchedWagons - Please try the following development build:

https://github.com/sumghai/MedPod/archive/440a2e39a9240d7db8c1c99d714f4de1c4148d09.zip

In my test save, it worked successfully for pawns with and without those VTE traits.

**Comment by sumghai** [comment]
Since there have been no comments and feedback, I'll assume the new feature can be rolled into the next update.
