### ISSUE TITLE
Conflict with Simple Slavery mod

### ISSUE THREAD

**Issue by ONEGUT** [sumghai/MedPod#6]
The med pod removed the hidden effect of slavery on one of my citizens. They still remained a colonist though. If you would like more information on my exact mod list or whatever you need let me know.

**Comment by sumghai** [comment]
There are 3~4 different versions of Simple Slavery in RimWorld mod ecosystem. Are you referring to [the 1.1 version maintained by MarkSill](https://steamcommunity.com/sharedfiles/filedetails/?id=2144935009)?

If so, looking at [the hediff definitions](https://github.com/MarkSill/Simple-Slavery/blob/master/Defs/HediffDefs/Hediffs_Slave.xml), the problem is that the `<isBad>` XML tag is hasn't been defined, which the game will then set to `true` by default - in other words, RimWorld itself is marking them as actual diseases, so the MedPod will end up "curing" them.

(Personally, I find it bizarre that slavery would be defined as a physiological health condition, but that's beside the point).

@MarkSill, to help resolve this compatibility issue with MedPod, could you please tag your Simple Slavery mod's `Enslaved`, `SlaveMemory`, `Hediff_EmancipateFix` and `Crypto_Stasis` hediffs with `<isBad>false</isBad>`?

**Comment by MarkSill** [comment]
Thanks for the tag, @sumghai. I just put out a new version that adds the `<isBad>` field to those hediffs.

**Comment by sumghai** [comment]
No worries, @MarkSill - thanks for getting back to us so quickly!

@ONEGUT - Can you please verify that MedPod now works with the latest update of Simple Slavery?

**Comment by sumghai** [comment]
@ONEGUT has failed verify the compatibility fixes in a timely manner, so I'm going to assume this is resolved.
