### ISSUE TITLE
EPOE optimizing nanobots causing infinite loop

### ISSUE THREAD

**Issue by quicksilverfox** [sumghai/MedPod#72]
**Describe the bug:**  

Organic/Instinct optimizing nanobots from EPOE-Forked are taking several days to do their job, causing pawn to be incapacited for that duration. MedPod enters an endless cycle of trying to treat the patient, but since it is not a detrimental status fails to do anything.

**Expected behavior:**  

Those hediffs should be ignored

**Steps to reproduce:**  

1. Apply Organic/Instinct optimizing nanobots to a pawn
2. See doctor carry patient to medpod after operation
3. See MedPod in endless cycle

**Additional information:**

## System and Game Configuration
**Operating System:** Windows 10 Home 21H2 64-bit 
**Physical RAM:** 32,0 GB
**RimWorld base game version:** 1.4.3542 
**RimWorld DLCs loaded:**  Royalty, Ideo, Biotech
**MedPod mod version:** 1.5.4
**MedPod mod downloaded from:** Steam
**Your mod list:** 
https://steamcommunity.com/workshop/filedetails/?id=1949064302

## Declaration

I hereby verify that:
- [x] I am running the latest version of the game, MedPod and its dependencies
- [x] I am NOT running any mods with known incompatibilities with MedPod
- [x] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if MedPod is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment]
Why aren't these fields completed?
![image](https://user-images.githubusercontent.com/4993380/202821559-c17f4790-7982-46ab-b356-b4f9514379d6.png)

**Comment by quicksilverfox** [comment]
Because I am pretty sure they are irrelevant. Also, it is kinda obvious that it does not happen if MedPod is disabled.

With low long Rimworld loads, it would take 15-30 minutes to do formalities. For me it is easier to just flick off medpod when I do that rare surgery when I actually have medpod even if the report would be dropped for formal reasons.

**Comment by sumghai** [comment]
> Because I am pretty sure they are irrelevant. Also, it is kinda obvious that it does not happen if MedPod is disabled.
> 
> With low long Rimworld loads, it would take 15-30 minutes to do formalities. For me it is easier to just flick off medpod when I do that rare surgery when I actually have medpod even if the report would be dropped for formal reasons.

I will check off the declaration for you, but please provide your computer's specifications.

If I otherwise make an exception for you, I would have to make an exception for everyone else's bug reports, which defeats the purpose of collecting data that could be used to determine whether a given issue is hypothetically affected by different computer specs. (There have been undocumented examples of RimWorld bugs that occur only in Linux and not Windows, and vice versa).

**Comment by quicksilverfox** [comment]
Okay. I've checked it and as expected it can be replicated with only official DLC, EPOE and MedPod.

You do know that for a very rare hypothetical case you are creating a quite high barrier for reports?

**Comment by sumghai** [comment]
EPOE's optimization hediffs renders pawns unconscious for some time after being implanted, so merely blacklisting, greylisting and usage blocking wouldn't work.

Rather than code up fragile logic to prevent hauling unconscious pawns with said hediffs to MedPods (and dealing with all the associated edge cases), I'll simply patch the max consciousness to 0.3, so that pawns can still get off the MedPods themselves, but temporarily suffer a significant debuff to their capacities.
