### ISSUE TITLE
Integration with Prison Labor

### ISSUE THREAD

**Issue by SchwarzFuchs** [sumghai/MedPod#81]
**Describe your idea:**

The idea is to blacklist "Removed legscuffs" and Removed Handscuff" from list of curable hediffs by MedPod.
**Why do you think your idea would be a good fit for MedPod?:**
It will fix the annoying moment when you need to manually remove cuffs after every time prisoner uses MedPod
**What alternatives/workarounds have you tried?**
There is no any
## Declaration

I hereby verify that:
- [x] I have searched the issue tracker and confirmed no-one else has already suggested my idea before
- [x] I understand that my idea will be closed and ignored if I do not fill this form properly, or if the mod author decides that my idea doesn't fit the scope of the mod

**Comment by sumghai** [comment]
Thank you for your suggestion - technically this is a bug, because from the way the Prison Labor mod works it looks like MedPods aren't supposed to be removing those hediffs.

I'll take a look and see whether this is something that needs to be fixed in MedPod, or a change made to Prison Labor itself.

**Comment by sumghai** [comment]
After assessing the situation, I'm going to message @Hazzer via Discord to ask if these hediffs could be tweaked on his end.

**Comment by sumghai** [comment]
@Hazzer informs me he will most likely fix the hediffs on his end, so I shouldn't need to do anything.
