### ISSUE TITLE
Regression: pawns with certain hediffs are not healed properly

### ISSUE THREAD

**Issue by volpol** [sumghai/MedPod#97]
**Describe the bug:**  
If an injured pawn has a a drug tolerance hediff then upon completed MedPod treatment the hediff is not removed and the health and pain values are not updated immediately. That is pawn is shown as having less than 100% health and the level of pain due to previous injuries.

**Expected behavior:**  
The pawns is completely healthy (i.e. 100% health) and pain free.

**Steps to reproduce:**  

1. Start a dev test and create necessary MedPod infrastructure
2. Have a pawn with a drug addiction and tolerance injured until medium/severe pain.
3. Have the pawn receive MedPod treatment. The health will remain below 100% and the pain is still there, with no visible cause.

**Additional information:**

The regression first appeared in 1.5.27, probably as the result of the logic rewrite. I did not initially consider not treated drug tolerance hediff as part of the bug, but it may be, as in the version 1.5.26 it is also removed after the treatment. I haven't tested beyond drug tolerance hediffs but I suspected all nonCriticalTreatableHediffs are affected.

## System and Game Configuration
**Operating System:** Linux 6.10.6 x86_64
**Physical RAM:** 32 GB
**RimWorld base game version:** 1.5.4243
**RimWorld DLCs loaded:** Royalty, Ideology, Biotech, Anomaly
**MedPod mod version:** 1.5.33
**MedPod mod downloaded from:** GitHub
**Your mod list:** Harmony 2.3.3.0, MedPod 1.5.33

## Declaration

I hereby verify that:
- [x] I am running the latest version of the game, MedPod and its dependencies
- [x] I am NOT running any mods with known incompatibilities with MedPod
- [x] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if MedPod is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by volpol** [comment]
So after some more testing it seems that the pawn gets off the MedPod before the treatment is finished, as there is no popup message from DischargePatient(), which was prevented by the induced coma in the older versions.

**Comment by sumghai** [comment]
Okay, I reproduced this issue with just Harmony, Core and MedPod.

- When a pawn with only an Alcohol Tolerance hediff and 10 damage applied via dev mode sought MedPod treatment, their acute injuries/hediffs were treated, but the MedPod did not run the cleanup methods that would reset pawn capacities and remove pain thoughts; furthermore, the drug tolerance hediffs were not actually being removed as intended.

- After commenting out the hediffs listed under `nonCriticalTreatableHediffs` in the mod's XML defs, the MedPod successfully ran the cleanup methods at the end of the treatment cycle, and as expected did not treat the drug tolerance hediffs.

My current theory is that in the logic rewrite, the "stay in MedPod" checks aren't accounting for `nonCriticalTreatableHediffs`, so pawns are voluntarily running off during treatment once all of their other obviously-bad hediffs had been treated.

Let's see what I can do about this...

**Comment by volpol** [comment]
I am just wondering if maybe bringing induced coma back is the way to go. There are also interactions with other mods to consider. For example with RescueeJoinsPlus (2177170403) where if a guest pawn is rescued to MedPod, the request to join pops up as soon as the pawn is no longer "incapable of walking" and the pawn hops off the the MedPod as soon as you accept which induced coma would have prevented.

**Comment by sumghai** [comment]
Here's what I've found upon further investigation:

- The base game uses `RestUtility.CanUseBedNow()` to determine whether a pawn can get into (or stay in) a given bed
- MedPod patches the aforementioned `CanUseBedNow()` method to add an additional check if the bed is a MedPod; this patch indirectly calls `MedPodHealthAIUtility.ShouldSeekMedPodRest()`
- `MedPodHealthAIUtility.ShouldSeekMedPodRest()`'s current logic says (among other things) that a pawn must go find a MedPod if they have "bad" hediffs that are not blacklisted (`neverTreatableHediffs`) or greylisted (`nonCriticalTreatableHediffs`)

It looks like the problem is with that last bit of logic, most likely left over from the older delta wave coma implementation:
- In 1.5.26, `ShouldSeekMedPodRest()` tells patients to go to a MedPod, and other logic makes the patient stay there until treatment is completed. `ShouldSeekMedPodRest()` thus rightfully ignores `nonCriticalTreatableHediffs`, as those hediffs are accounted for elsewhere.
- From 1.5.27 onwards, the new logic uses `ShouldSeekMedPodRest()` for both "going to" and "staying in" MedPods. This correctly prevents pawns from going to MedPods if they *only* have `nonCriticalTreatableHediffs`, but now also incorrectly tells pawns to leave MedPods if they only have `nonCriticalTreatableHediffs` remaining.

I think `ShouldSeekMedPodRest()` needs to be amended so that
- If the pawn is currently not in a MedPod, they should only go to a MedPod if they have any bad hediffs other than those in `nonCriticalTreatableHediffs`
- Once the pawn is already in a MedPod, they should stay even if they only have any `nonCriticalTreatableHediffs`

> I am just wondering if maybe bringing induced coma back is the way to go. 

That would be a pretty terrible idea.

The logic rewrite eliminated the oft-dreaded and long-running "pawns stuck forever in MedPod" bug, and offered significant performance improvements. Going back to the induced coma implementation would mean removing most of the desired optimizations.

> There are also interactions with other mods to consider. For example with RescueeJoinsPlus (2177170403) where if a guest pawn is rescued to MedPod, the request to join pops up as soon as the pawn is no longer "incapable of walking" and the pawn hops off the the MedPod as soon as you accept which induced coma would have prevented.

That is a separate problem, and should not be discussed in this issue.

**Comment by volpol** [comment]
>The logic rewrite eliminated the oft-dreaded and long-running "pawns stuck forever in MedPod" bug, and offered significant performance improvements. Going back to the induced coma implementation would mean removing most of the desired optimizations.

Thanks for the explanations. Though even with the new logic I still occasionally get pawns stuck in the MedPod in the Regenerating phase with progress going well over 100%. If I ever learn how to reproduce that reliably I will open a new issue.

> That is a separate problem, and should not be discussed in this issue.

Fair.
Good luck.

**Comment by sumghai** [comment]
@volpol - Please try the following dev build, and let me know if it helps:

https://github.com/sumghai/MedPod/archive/b9798d9f297005cf8a83016b252323a36c16cf34.zip

In my own tests:
- Pawns with only critical hediffs complete treatment successfully
- Pawns with only non-critical hediffs don't use MedPods (as intended)
- Pawns with both critical and non-critical hediffs complete treatment successfully (they come to the MedPod because of the critical hediffs, and stay until the non-critical hediffs are also healed as well)

**Comment by volpol** [comment]
The latest build fixes the issue for me as well. Thanks.

**Comment by sumghai** [comment]
Okay, I'll have this folded into the next update. Thanks!
