### ISSUE TITLE
Rot stink exposure can cause the pawn to leave in the middle of treatment

### ISSUE THREAD

**Issue by volpol** [sumghai/MedPod#98]
**Describe the bug:**  
A pawn with rot stink exposure and injuries receiving treatment in a MedPod will run off before treatment is done, causing the same behavior as the issue #97

**Expected behavior:**  
A pawn with rot stink exposure and injuries receiving treatment in a MedPod stays put until the treatment is completed successfully and rot stink exposure as well as the injuries are removed.

**Steps to reproduce:**  

1. Start a dev test and create necessary MedPod infrastructure.
2. Give a pawn rot stink exposure hediff and increase severity until at least 6%
3. Injure pawn (using 10 damage dev tool).
4. Have the pawn receive MedPod treatment. 

**Additional information:**

Tested with dev build b9798d9f297005cf8a83016b252323a36c16cf34 initially, but current master is also affected.
Adding `LungRotExposure` to the `nonCriticalTreatableHediffs` fixes the problem for me.

## System and Game Configuration
**Operating System:** Linux 6.10.6 x86_64
**Physical RAM:** 32 GB
**RimWorld base game version:** 1.5.4243
**RimWorld DLCs loaded:** none
**MedPod mod version:** dev build b9798d9f297005cf8a83016b252323a36c16cf34
**MedPod mod downloaded from:** GitHub
**Your mod list:** Harmony 2.3.3.0, Core, MedPod b9798d9f297005cf8a83016b252323a36c16cf34

## Declaration

I hereby verify that:
- [x] I am running the latest version of the game, MedPod and its dependencies
- [x] I am NOT running any mods with known incompatibilities with MedPod
- [x] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if MedPod is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by volpol** [comment]
Certain hediffs, that are probably not supposed to be treatable, like `PsychicSuppression` from Royalty, seem to be able to trigger this behavior as well. The fix is likely to be more involved that simply adding more entries to the `nonCriticalTreatableHediffs` list.

**Comment by sumghai** [comment]
@volpol - I've added `LungRotExposure` and `PsychicSuppression` to the `nonCriticalTreatableHediffs` greylist.

Do note that for `PsychicSuppression`, if there is a Psychic Suppressor active on the map, pawns will most likely get stuck inside the MedPod.

I did look into whether there was a more universal solution that did not necessitate patching the `nonCriticalTreatableHediffs` list, and one possibility was having `MedPodHealthAIUtility.ShouldSeekMedPodRest()` read back data from the MedPod currently used by the patient to see if there are any remaining hediffs left in the treatment todo list. However, I'm not sure how performant frequently looking up a changing list would be.

As I don't necessarily play with every feature of every DLC and I may not be familiar with every hediff, for the time being, it would be best for players to report specific hediffs causing problems, so that I can assess how to deal with them on a case-by-case basis.
